#! /bin/sh

panel &
sxhkd &

bspc config focused_border_color $TERM_BACKGROUND
bspc config normal_border_color $TERM_BACKGROUND

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d          

bspc desktop $(bspc query -D | head -n 2 | tail -n 1) -l monocle

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2 layout=monocle
bspc rule -a mpv state=floating border=off
bspc rule -a Wine state=floating border=off
bspc rule -a MPlayer state=floating border=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a X2GoAgent border=off
bspc rule -a explorer.exe desktop=^8 border=off
