#! /bin/sh
#
# Example panel for lemonbar

. panel_colors
. panel_info

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		C*)
			# clock output
			item=${line#?}
			clock="%{B$COLOR_DEFAULT_BG} %{+u}%{U$COLOR_CLOCK_UG}%{F$COLOR_SYS_ICON}$ICON_CLOCK%{B-}%{F$COLOR_SYS_FG} ${item}%{-u} %{F-}"
			;;
		D*)
			# date output
			item=${line#?}
			date="%{F$COLOR_SYS_FG}%{B$COLOR_DEFAULT_BG} %{+u}%{U$COLOR_DATE_UG}%{F$COLOR_SYS_ICON}$ICON_CALENDAR%{B-}%{F$COLOR_SYS_FG} ${item}%{-u} %{F-}"
			;;
		T*)
			# xtitle output
			item=${line#?}
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_DEFAULT_BG}%{+u}%{U$COLOR_TITLE_UG}${item}%{-u} %{B-}%{F-}"
			;;
		M*)
			# memory output
			item=${line#?}
			memory="%{F$COLOR_SYS_FG}%{B$COLOR_DEFAULT_BG} %{+u}%{U$COLOR_MEM_UG}%{F$COLOR_SYS_ICON}$ICON_MEMORY%{B-}%{F$COLOR_SYS_FG} ${item}%{-u} %{F-}"
			;;	
		B*)
			# battery output
			item=${line#?} ; level=$(echo $item | cut -d "%" -f2) ; state=$(echo $item | cut -d " " -f1)
			case $level in 
				Full) ;;
				Normal) ;;
				Low) ;;
			esac
			case $state in 
				U) ;;
				F) ;;
				C) ;;
				D) ;;
			esac 
			item=$(echo $item | cut -d "%" -f1 | cut -d " " -f2)"%"
			bat="%{F$COLOR_SYS_FG}%{B$COLOR_DEFAULT_BG} %{+u}%{U$COLOR_BAT_UG}%{F$COLOR_SYS_ICON}$ICON_BATTERY_FULL%{B-}%{F$COLOR_SYS_FG} ${item}%{-u} %{F-}"
			;;

		c*)
			# volume output	
			item=$(sound_volume) ; state=$(sound_switch)
			case $state in 
				on) icon=$ICON_VOLUME_HIGH;;
				off) icon=$ICON_VOLUME_OFF;;
			esac
			vol="%{F$COLOR_SYS_FG}%{B$COLOR_DEFAULT_BG} %{+u}%{U$COLOR_VOL_UG}%{F$COLOR_SYS_ICON}$icon%{B-}%{F$COLOR_SYS_FG} ${item}%{-u} %{F-}"
			;;
		N*)
			# network output
			IFS=':';wifi="off";eth="off";vpn="off"
			for item in ${line#?} ; do
				case $item in
					W*) wifi=${item#?} ;;
					E*) eth=${item#?} ;;
					V*) vpn=on ;;
				esac
			done
			net="%{F$COLOR_SYS_FG}%{B$COLOR_DEFAULT_BG} %{+u}%{U$COLOR_NET_UG}%{F$COLOR_SYS_ICON}$ICON_VPN%{B-}%{F$COLOR_SYS_FG} $vpn %{F$COLOR_SYS_ICON}$ICON_WIFI%{F$COLOR_SYS_FG} $wifi %{F$COLOR_SYS_ICON}$ICON_ETHERNET%{F$COLOR_SYS_FG} $eth%{-u} %{F-}"
			;;

		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								UC=""
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								UC="%{-u}"
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								UC=""
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
								UC="%{-u}"
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								UC=""
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								UC="%{-u}"
								;;
						esac
						UG=$COLOR_DESKTOP_UG
						BG=$COLOR_DEFAULT_BG
						#%{T2}%{F#ffffff}/%{F-}%{T-}
						wm="%{+u}${wm}%{F${FG}}%{B${BG}}%{U${UG}}%{A:bspc desktop -f ${name}:} ${name} ${UC}%{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_DEFAULT_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm}%{c}%{r}${net}${memory}${vol}${bat}${date}${clock}"
done
